### ISSUE TITLE
Small test issue on upload control

### ISSUE THREAD

**Issue by YvesR** [Components-care/react-components#3]
Installed and testing project.
Tested on http://localhost:9009/?path=/story/standalone-fileupload--file-upload-story.

Small things to fix or improve:
- [x] If I add files and file name to long it will be cropped with ..., but there is no mouse-over with full name.
- [x] If I add same file again, it will be added again, there is no duplicate checkup to replace
- ~~drag & drop outside the control will unload the page. Probably not part of control it self, but page needs to handle this.~~
- ~~Extension not allowed alert should be part of the control, at the moment it comes only as error message and developer has to handle this extra.~~

**Comment by TQjona** [comment]
- Filename Tooltip implemented
- Duplicate handling implemented
- Other two things will be handled as part of dialog and form systems provided by the framework, therefore not part of this issue
