### ISSUE TITLE
Single and multiple controls layout change request

### ISSUE THREAD

**Issue by YvesR** [Components-care/react-components#4]
Test results storyboard new Controls:

![screenshot](https://user-images.githubusercontent.com/4928882/88785640-c1cb2300-d191-11ea-9663-e35093e82740.png)

**Icons**
The space left and right for icons are to big. Reduce by 50%, if possible make the default adjustable by properties

![margins](https://user-images.githubusercontent.com/4928882/88785756-e32c0f00-d191-11ea-975e-8aaf7b8dfffd.png)

**Shadows**

Controls use different shadow weight and effect
By default should be **no** shadow and optional can activate, but if shadow, then equal weight and direction.

![schatten](https://user-images.githubusercontent.com/4928882/88785914-1a9abb80-d192-11ea-91a0-84ffdf6e9e67.png)

**Multiple selectd values**

Shown like this

![multi](https://user-images.githubusercontent.com/4928882/88786016-3bfba780-d192-11ea-9f09-709029d88136.png)

Should be like this

![screenshot 1](https://user-images.githubusercontent.com/4928882/88786068-5170d180-d192-11ea-9cc3-7243d33f6588.png)

**Features**

Storyboard not show this, so I mention those requirements if not already available:
- Delete button confirm yes/no optional
- Icon optional click event / url
- Text optional click event / url

**Comment by TQjona** [comment]
styles fixed, requested features added
